version: '3'

services:
  hof:
    image: hof
    container_name: hof-asp-net
    restart: always
    tty: true
    ports:
      - "5112:5112"
    depends_on:
      - postgres-db
    networks:
      - my-network

  postgres-db:
    image: postgres:latest
    container_name: postgresql-db
    restart: always
    environment:
      - POSTGRES_USER=artem
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=HOF_Test
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - my-network

networks:
  my-network: